[package]
name        = "curve_intersections_demo"
version     = "0.1.0"
authors     = ["Andrew Hunter <andrew@logicalshift.co.uk>"]
description = "Demonstrates curve intersections in flo_curves"
edition     = "2018"

[dependencies]
flo_curves  = "0.6"
flo_draw    = "0.4"
