[package]
name        = "arithmetic_demo"
version     = "0.1.0"
authors     = ["Andrew Hunter <andrew@logicalshift.co.uk>"]
description = "Demonstrates path arithmetic in flo_curves"
edition     = "2018"

[dependencies]
flo_curves  = "0.5"
flo_draw    = "0.3"
