[workspace]
members = [
    "offset",
    "walk",
    "distort",
    "arithmetic",
    "curve_intersections",
    "remove_interior_points"
]

[patch.crates-io]
flo_curves              = { path = ".." }
